import Head from 'next/head';
import { useRouter } from 'next/router';
export default function Home(params) {
  const router = useRouter();
  // Host available from router if blocking or fallback
  const { host, path = [] } = router.query;

  // Or params
  console.log(params);

  return (
    <div>
      <Head>
        <title>Next Multi Host Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Showing /{path.join('/')} from {host}
      </h1>
    </div>
  );
}

export async function getStaticProps(context) {
  // Available on server render
  console.log(context.params);

  return {
    props: {
      host: context.params.host || null,
      path: context.params.path || null,
    },
  };
}

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: 'blocking',
  };
}
