import Head from 'next/head';
import Link from 'next/link';

import { useRouter } from 'next/router';
export default function Cached({ host, id, time }) {
  const router = useRouter();

  // Host available on query from router if blocking or fallback
  const query = router.query;

  // Or params
  console.log(host, id, time, query);

  return (
    <div>
      <Head>
        <title>Next Multi Host Cache Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href={host.includes('localhost') ? 'http://localhost:3000/' : 'https://next-multi-host.vercel.app/'}>Host 1</Link>
        {' - '}
        <Link href={host.includes('localhost') ? 'http://another.localhost:3000/' : 'https://next-multi-host-acorcutt.vercel.app/'}>Host 2</Link>
      </div>
      <h1>Host: {host}</h1>
      <p>
        <b>Generated At:</b>
        <i>{time}</i>
        {' - '}
        <b>Post:</b>
        <i>{id}</i>
      </p>
      <div>
        <Link href="/">Home</Link> - <Link href="/posts/a">Static Built A</Link> - <Link href="/posts/b">Not Static B</Link>
      </div>
    </div>
  );
}

export async function getStaticProps(context) {
  // Available on server render
  console.log('getStaticProps', context);

  const host = context.params.host;
  const id = context.params.id;

  const time = Date.now();

  return {
    props: {
      host,
      id,
      time,
    },
    // revalidate: 10,
  };
}

export async function getStaticPaths() {
  return {
    paths: [
      // Include host in static params!
      { params: { id: 'a', host: 'localhost' } },
      { params: { id: 'a', host: 'next-multi-host.vercel.app' } },
      { params: { id: 'a', host: 'next-multi-host-acorcutt.vercel.app' } },
    ],
    fallback: 'blocking',
  };
}
