import Head from 'next/head';

import { useRouter } from 'next/router';

import Header from 'components/header';
import Footer from 'components/footer';
export default function CatchAll({ host, time, path }) {
  const router = useRouter();

  // Host available on query from router if blocking or fallback
  const query = router.query;

  // Or params
  console.log('CatchAll', host, time, path, query);

  return (
    <div>
      <Head>
        <title>Next Multi Host Catch All Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header host={host} />
      <h1>
        Catch All With Host - Host: <i>{host}</i>
      </h1>
      <p>
        Path: <i>/{path}</i> {' - '}
        Generated At: <i>{time}</i>
      </p>
      <Footer />
    </div>
  );
}

export async function getStaticProps(context) {
  // Available on server render
  console.log('getStaticProps', '[[...path]].js', context);

  // Host is available if this catchall catches it
  const host = context.params.host;
  const path = [context.params.part, ...(context.params.path || [])].filter(Boolean).join('/');
  const time = Date.now();
  return {
    props: {
      host,
      path,
      time,
    },
    //revalidate: 10,
  };
}

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: 'blocking',
  };
}
